name: my_project_environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # Or your preferred Python version
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - folium
  - shap
